<a href="https://colab.research.google.com/github/zain4cs/ML_Pipelines/blob/main/ML_Pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.drop(columns=['PassengerId', 'Name','Ticket','Cabin'], inplace=True)

In [ ]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

____________________

**Train-Test-Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                    df['Survived'],
                                                    test_size=0.2,
                                                    random_state=42)

In [ ]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Age         177
Embarked      2
Pclass        0
Survived      0
Sex           0
SibSp         0
Parch         0
Fare          0
dtype: int64

____________________

**Apply Simple Imputer**

In [ ]:
si_age = SimpleImputer()
si_Embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_Embarked = si_Embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_Embarked = si_Embarked.transform(X_test[['Embarked']])

_________________________________

**Apply One-Hot-Encoder**

In [ ]:
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_Embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_Embarked = ohe_Embarked.fit_transform(X_train[['Embarked']])

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_Embarked  = ohe_Embarked.transform(X_test[['Embarked']])

___________________________

In [ ]:
X_train_rem = X_train.drop(columns=['Sex', 'Age','Embarked'])
X_test_rem = X_test.drop(columns=['Sex', 'Age','Embarked'])

_________________

**Concatenate the Columns**

In [ ]:
X_train_transformed = np.concatenate((X_train_age, X_train_sex , X_train_Embarked , X_train_rem ), axis=1)
X_test_transformed = np.concatenate((X_test_age, X_test_sex, X_test_Embarked , X_test_rem), axis=1)

In [ ]:
X_train_transformed.shape

(712, 11)

__________________

**Apply Decision Tree**

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

___________________

**Check Accuracy**

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.776536312849162

________________________

**Now Use Pickle:**

> In Machine Learning, Pickle is a Python module used to save your trained model to a file so you can use it later without having to re-train it.

In [ ]:
import pickle

In [ ]:
pickle.dump(ohe_sex, open('/content/drive/MyDrive/Datasets/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_Embarked, open('/content/drive/MyDrive/Datasets/ohe_Embarked.pkl', 'wb'))
pickle.dump(clf, open('/content/drive/MyDrive/Datasets/clf.pkl','wb'))